add data_mask method
ShanghaiITVolunteer/AntigenClassifier pull request #1
Opened 2022-05-06 15:53 UTC by livingbody

## method:
def data_mask(source_dir, target_dir, key_words=['2019', 'ANC', "C", "T", 'S', "c", "t", "s"]):
## parameter

- source_dir: 待脱敏图片文件夹
- target_dir: 脱敏后图片保存文件夹
- key_words： 检测盒的基本信息（不用mask掉文字列表)

2022-05-06 16:02 UTC, wj-Mcat requested changes
代码很棒，有一些小问题我们可以来讨论

2022-05-06 16:02 UTC, wj-Mcat commented on src/masking/data_mask.py
> +import cv2
这两个package 你可以添加到requirements.txt文件当中

2022-05-06 16:02 UTC, wj-Mcat commented on src/masking/data_mask.py
> +    data_mask(source_dir="antigen-images", target_dir="saved")
这部分测试代码你可以尝试用pytest写一些简单的单元测试代码，你可以参考`test_smoke.py`文件，甚至说参考[python-wechaty test](https://github.com/wechaty/python-wechaty/tree/master/tests)。

这些工具对于企业和开源项目来说比较重要，也是比人理解你项目的一个重要途径。

2022-05-06 16:03 UTC, wj-Mcat commented
你可以从主分支上重新来取一下代码，里面我添加了CI的一些配置

2022-05-06 16:10 UTC, livingbody commented on src/masking/data_mask.py
> +    data_mask(source_dir="antigen-images", target_dir="saved")
收到，在学习中。

2022-05-07 05:27 UTC, wj-Mcat requested changes
我在我本地遇到了内存溢出的问题。

2022-05-07 05:27 UTC, wj-Mcat commented on src/masking/data_mask.py
> +        text_thresh=0.3)  # 识别中文文本置信度的阈值；
如果照片过大的话，这里会直接导致内存溢出，所以这里如果能够设置成batch-loader的方式，我感觉会更好

2022-05-07 05:28 UTC, wj-Mcat commented
You can also try to make CI green, and make the code testable.

2022-05-07 11:06 UTC, livingbody commented on src/masking/data_mask.py
> +        text_thresh=0.3)  # 识别中文文本置信度的阈值；
嗯，感觉其实没必要过大尺寸，加resize？

2022-05-09 09:25 UTC, wj-Mcat commented
Thanks for contribution which is a great script for masking info.

2022-05-09 09:25 UTC, merged